name: msbuild

on:
  workflow_dispatch:
  # Trigger the workflow on push or pull request - but only for the main branch
  push:
  pull_request: 

defaults:
  run:
    shell: PowerShell

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  DO_LIST: True

jobs:
  build-on-windows:
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix

    runs-on: windows-2025

    steps:
    - name: install
      run: |
          choco install wget innoextract --no-progress

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Clone dependencies
      working-directory: ${{ runner.workspace }}
      run: |
          cd "${{ runner.workspace }}"
          git clone https://github.com/libusb/libusb libusb
          git clone https://github.com/GerHobbelt/pthread-win32 pthread-win32
    - name: List clone 
      if: ${{ env.DO_LIST == 'True' }}
      run: |
          echo "********************************************"
          ls
          echo "********************************************"
          ls -Path "${{ runner.workspace }}"
          echo "********************************************"
          #ls -Recurse -Exclude ".git,debian" -Path "${{ runner.workspace }}/pthread-win32" 
          #echo "********************************************"
          #ls -Recurse -Exclude ".git,debian" -Path "${{ runner.workspace }}/libusb"
          #echo "********************************************"
          #ls -Recurse -Exclude ".git,debian" -Path "${{ github.workspace }}"
          #echo "********************************************"
          
    - name: Build pthread-win32
      working-directory: ${{ runner.workspace }}
      run: |
          cd pthread-win32
          cmake -B shared `
                -DBUILD_SHARED_LIBS=ON `
                -DCMAKE_INSTALL_PREFIX=shared
          cmake --build shared `
                --config Release `
                --target install
                
    - name: List pthread
      if: ${{ env.DO_LIST == 'True' }}
      run: |
          echo "********************************************"
          ls 
          echo "********************************************"
          ls -Path "${{ runner.workspace }}"
          echo "********************************************"
          ls -Recurse -Exclude ".git,debian" -Path  "${{ runner.workspace }}/pthread-win32" 
        
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: libusb Configure Visual Studio and CMake
      working-directory: ${{runner.workspace}}/libusb
      run: |
          msbuild msvc/libusb.sln `
                /m `
                -property:Configuration=Release `
                -property:Platform=x64

    - name: List libusb
      if: ${{ env.DO_LIST == 'True' }}
      run: |
          echo "********************************************"
          ls -Recurse -Exclude ".git,debian"  -Path "${{ runner.workspace }}/libusb"
          echo "********************************************"
          cd ..

    - name: RTL-SDR configure build
      working-directory: ${{github.workspace}}
      run: |
        #mkdir ${{github.workspace}}/build
        cmake -B build_rtl-sdr_udpsrv -S . -A x64 -DCMAKE_BUILD_TYPE=Release --fresh `
              -DLIBUSB_LIBRARIES=${{runner.workspace}}/libusb/build/v143/x64/Release/dll/libusb-1.0.lib `
              -DLIBUSB_PKG_LIBRARY_DIRS=${{runner.workspace}}/libusb/build/v143/x64/Release/dll/libusb-1.0.lib  `
              -DLIBUSB_INCLUDE_DIRS=${{runner.workspace}}/libusb/libusb `
              -DLIBUSB_INCLUDE_DIR=${{runner.workspace}}/libusb/libusb `
              -DTHREADS_PTHREADS_INCLUDE_DIR=${{runner.workspace}}/pthread-win32 `
              -DTHREADS_PTHREADS_LIBRARY=${{runner.workspace}}/pthread-win32/shared/lib/pthreadVC3.lib `
              -DTHREADS_PTHREADS_WIN32_LIBRARY=${{runner.workspace}}/pthread-win32/shared/lib/pthreadVC3.lib `
              -DCMAKE_THREAD_LIBS_INIT=${{runner.workspace}}/pthread-win32/shared/lib/pthreadVC3.lib `
              /DPROVIDE_UDP_SERVER#ON
              ## --log-level=DEBUG --trace-expand --debug-find 

    - name: List rtlsdr 1
      if: ${{ env.DO_LIST == 'True' }}
      run: |
        ls -Recurse -Exclude ".git,libusb,pthread-win32,debian"

    - name: cmake 
      run: |
        cmake --build build_rtl-sdr_udpsrv --config Release --verbose
        echo "*********************************************"

    - name: List cmake 1
      if: ${{ env.DO_LIST == 'True' }}
      run: |
        ls 
        ls -Recurse -Exclude ".git,libusb,pthread-win32,debian"
        
    - name: Collect files to distribute
      working-directory: ${{github.workspace}}
      run: |
        mkdir dist/bin
        cp build_rtl-sdr_udpsrv/src/Release/* dist/bin
        cp   ${{ runner.workspace }}/pthread-win32/shared/bin/*  dist/bin
        cp   ${{ runner.workspace }}/libusb/build/v143/x64/Release/dll/*.dll dist/bin
        ls -Path dist/bin


    #- name: cmake install
    #  run: |
    #    cmake --install build_rtl-sdr_udpsrv --prefix dist --verbose
    #    ###echo "* ${{github.workspace}} : `git show --format='%h (%s, %as)' --no-patch`" >> ${{github.workspace}}/release_notes.md

    - name: List after build
      if: ${{ env.DO_LIST == 'True' }}
      run: |
          ## cat "${{ github.workspace }}/build/src/cmake_install.cmake"
          ls -Path "${{ runner.workspace }}"
          echo "*********************************************"
          ls -Path "${{ github.workspace }}"
          echo "*********************************************"
          ls  -Path "${{ github.workspace }}/build"
          echo "*********************************************"
          ls  -Recurse -Exclude ".git,libusb,pthread-win32,debian" -Path "${{ github.workspace }}/build"
          echo "*********************************************"
          echo "*********************************************"
          ls -Recurse -Exclude ".git,,libusb,pthread-win32,debian,build" -Path "${{ github.workspace }}"
          echo "*********************************************"
          cat "${{ github.workspace }}/cmake_install.cmake"
          echo "*********************************************"
          cat "${{ github.workspace }}/build/cmake_install.cmake"
          echo "*********************************************"
          cat "${{ github.workspace }}/build\src\rtlsdr.vcxproj"
          echo "*********************************************"

    - name: Collect files to distribute
      working-directory: ${{github.workspace}}
      run: |
        cp   ${{ runner.workspace }}/pthread-win32/shared/bin/*  dist/bin
        cp   ${{ runner.workspace }}/libusb/build/v143/x64/Release/dll/*.dll dist/bin

    - name: package and upload
      uses: actions/upload-artifact@v4
      with:
        name: librtlsdr_librtlsdr_w64_udpsrv_msdist
        path: |
            dist/lib/rtlsdr.lib
            dist/bin
            dist/include
            COPYING
            AUTHORS
            README





